port: 4003
url: "https://alainparadis.github.io/emmet"
baseurl: "/emmet"
github_username: alainparadis
github_repo: "https://alainparadis.github.io/emmet/"
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  articles:
    output: true
    permalink: /articles/:title/