port: 4003
title: Emmet's Portfolio
email: emmet@paradisfamily.ca
description: >-
  This is Emmet Paradis' writing portfolio site. It features the best of his projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: alainparadis
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
